[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

	[buildPlans.iosevka-custom.variants]
	inherits = "ss20"

		[buildPlans.iosevka-custom.variants.design]
		capital-g = "toothed-inward-serifed-capped"
		capital-l = "motion-serifed"
		capital-m = "slanted-sides-hanging-motion-serifed"
		capital-n = "motion-serifed"
		capital-p = "closed-motion-serifed"
		capital-q = "open-swash"
		capital-r = "straight-motion-serifed"
		capital-s = "unilateral-serifed"

	[buildPlans.iosevka-custom.ligations]
	inherits = "dlig"
